# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{abstract_analyzer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark McSpadden"]
  s.date = %q{2009-10-28}
  s.email = %q{markmcspadden@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "abstract_analyzer.gemspec",
     "lib/LICENSE",
     "lib/abstract_analyzer.rb",
     "lib/dash_analyzer.rb",
     "lib/dash_analyzer/base.rb",
     "lib/dash_analyzer/dash_extensions.rb",
     "lib/dash_analyzer/view.rb",
     "lib/middleware.rb",
     "lib/middleware/rails.rb",
     "lib/middleware/rails/dash.rb",
     "lib/view.rb",
     "test/lib/dash_analyzer/test_base.rb",
     "test/lib/dash_analyzer/test_dash_extensions.rb",
     "test/lib/dash_analyzer/test_view.rb",
     "test/lib/middleware/rails.rb",
     "test/lib/middleware/rails/dash.rb",
     "test/lib/test_dash_analyzer.rb",
     "test/lib/test_middleware.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/garlandgroup/abstract-analyzer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A rack based app analyzer}
  s.test_files = [
    "test/lib/dash_analyzer/test_base.rb",
     "test/lib/dash_analyzer/test_dash_extensions.rb",
     "test/lib/dash_analyzer/test_view.rb",
     "test/lib/middleware/rails/dash.rb",
     "test/lib/middleware/rails.rb",
     "test/lib/test_dash_analyzer.rb",
     "test/lib/test_middleware.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

